storePassword=180774
keyPassword=180774
keyAlias=key
#storeFile=/Users/balanzashook/Documents/LlavesFlutter/Cuatro_platos/key.jks
storeFile=D://Programas Flutter//TRABAJO//Llaves-Flutter//Cuatro_platos//key.jks